import { api, command } from "./client";
import { bearer } from "../auth/store";
export type StaffImportField="name"|"phone"|"active"|"roomRole"|"team"|"bedroom"|"transportation"|"allergies"|"drugAllergies"|"healthIssues"|"foodRestrictions"|"dailyMedication"|"healthNotes";
export interface StaffImportReview {id:string;row:number;kind:"phone"|"duplicate"|"bedroom"|"roomRole"|"inactive";field:string;memberName:string;original:string;value:string;skip:boolean;resolved:boolean;context?:string;existingId?:string;existingName?:string;existingPhone?:string|null;options?:{id:string;label:string}[]}
export interface StaffImport {id:string;fileName:string;status:"needs_mapping"|"analyzing"|"review"|"ready"|"importing"|"completed"|"error";columns:{source:string;target:StaffImportField|null;confidence:number;samples:string[]}[];reviews:StaffImportReview[];preview:Record<string,unknown>[];skipped:Record<string,unknown>[];createdItems:{kind:string;id:string;label:string;draft:boolean}[];error:string}
export async function listStaffImportFields(token:string){return (await api<{fields:{key:StaffImportField;label:string}[]}>("/api/staff-imports/fields",{headers:bearer(token)})).fields}
export async function analyzeStaffFile(token:string,file:File,mapping?:Record<string,string|null>){const body=new FormData();body.append("file",file);if(mapping)body.append("mapping",JSON.stringify(mapping));return (await api<{import:StaffImport}>("/api/staff-imports/analyze",{method:"POST",headers:bearer(token),body})).import}
export async function createImportStaffDraft(token:string,id:string,reviewId:string,phone:string){return command<{staff:{id:string;name:string;phone:string};import:StaffImport}>(`/api/staff-imports/${id}/members`,{method:"POST",headers:{...bearer(token),"content-type":"application/json"},body:JSON.stringify({reviewId,phone})},["staff"])}
export async function applyStaffImport(token:string,id:string,file:File,delta:Record<string,{value?:string;skip?:boolean}>,sendWelcomes:boolean){const body=new FormData();body.append("file",file);body.append("delta",JSON.stringify(delta));body.append("sendWelcomes",String(sendWelcomes));return command<{inserted:number;updated:number;loginsCreated:number;welcomeQueued:number;skipped:unknown[]}>(`/api/staff-imports/${id}/apply`,{method:"POST",headers:bearer(token),body},["staff","bedrooms","teams","transports","categories"])}
