import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import Breadcrumbs from "../../components/Breadcrumbs";
import { BackGlyph, CheckGlyph, DownloadGlyph, EllipsisGlyph, EyeGlyph, SkipGlyph } from "../../components/Glyph";
import { ICONS } from "../../icons";
import { useCollectionOrEmpty } from "../../store";
import { analyzeStaffFile, applyStaffImport, createImportStaffDraft, getStaffImportProgress, listStaffImportFields, type StaffImport, type StaffImportField } from "../../api/staffImports";
import ImportPhaseBar, { STAFF_PHASES, type ImportPhaseInfo } from "../../components/ImportPhaseBar";
import { formatBrazilPhoneClient } from "../../phoneFormat";
import { maskBrazilPhone } from "../../phone";
import PhoneInput from "../../components/PhoneInput";
import Toggle from "../../components/Toggle";
import NoPillIcon from "../../components/NoPillIcon";
import { peekPendingImportFile, useFileDrop } from "../../hooks/useFileDrop";
import type { Category } from "../../api/categories";
import { useI18n } from "../../i18n";

type Delta=Record<string,{value?:string;skip?:boolean}>;
const ID=/^(?:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}|[a-f0-9]{24})$/i;
const ID_HEADER=/^(?:id|uuid|guid|_id|[a-z0-9]+_id|[a-z0-9]+ id)$/i;
const isIgnoredColumn=(source:string)=>ID_HEADER.test(source.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim());
const unassignedColumns=(columns:{source:string;target:string|null;samples:string[]}[])=>columns.filter((c)=>!c.target&&c.samples.length&&!isIgnoredColumn(c.source));

type Stage="file"|"mapping"|"review"|"summary"|"done";
type Review=StaffImport["reviews"][number];

const REVIEW_LABEL:Record<Review["kind"],string>={
 duplicate:"Cadastros repetidos",phone:"Telefones",bedroom:"Quartos",roomRole:"Função no quarto",inactive:"Ativos",
};
const REVIEW_ORDER:Review["kind"][]=["duplicate","phone","bedroom","roomRole","inactive"];
const isRichDup=(item:Review)=>item.kind==="duplicate"&&!!item.existingData;
const isSheetPhoneConflict=(item:Review)=>item.kind==="duplicate"&&!item.existingData;
const phoneConflictKey=(item:Review)=>{const phone=typeof item.incomingData?.phone==="string"?item.incomingData.phone:"";return phone||item.original||`row:${item.row}`;};
const conflictDigits=(value:string)=>value.replace(/\D/g,"").replace(/^55/,"");
function sheetConflictPhone(item:Review,d?:{value?:string;skip?:boolean}):{phone:string;complete:boolean}|null{
 if(d?.skip)return null;
 const value=d?.value??"";
 if(value==="blank")return {phone:"",complete:true};
 if(!value||value==="keep-phone")return {phone:conflictDigits(phoneConflictKey(item)),complete:true};
 const digits=conflictDigits(value);
 return {phone:digits,complete:digits.length===0||digits.length===11};
}
function sheetConflictReady(group:Review[],delta:Delta){
 const phones:string[]=[];
 for(const item of group){
  const resolved=sheetConflictPhone(item,delta[item.id]);
  if(!resolved)continue;
  if(!resolved.complete)return false;
  if(resolved.phone)phones.push(resolved.phone);
 }
 return new Set(phones).size===phones.length;
}

export default function StaffImportPage({token,onBack}:{token:string;onBack:()=>void}){
 const {tx}=useI18n();
 const [file,setFile]=useState<File|null>(null),[data,setData]=useState<StaffImport|null>(null),[fields,setFields]=useState<{key:StaffImportField;label:string}[]>([]);
 const [stage,setStage]=useState<Stage>("file"),[delta,setDelta]=useState<Delta>({}),[reviewIndex,setReviewIndex]=useState(0);
 const [previewOpen,setPreviewOpen]=useState(true),[declinedCategoryIds,setDeclinedCategoryIds]=useState<Set<string>>(()=>new Set()),[duplicateChoice,setDuplicateChoice]=useState<"update"|"keep"|"merge"|"">("");
 const [savedDrafts,setSavedDrafts]=useState<Record<string,string>>({});
 const [done,setDone]=useState("");
 const [busy,setBusy]=useState(false),[analyzing,setAnalyzing]=useState(false),[phase,setPhase]=useState<ImportPhaseInfo|null>(null),[error,setError]=useState("");
 const bedrooms=useCollectionOrEmpty("bedrooms"),teams=useCollectionOrEmpty("teams"),transports=useCollectionOrEmpty("transports"),categories=useCollectionOrEmpty("categories"),staff=useCollectionOrEmpty("staff");
 const fileInput=useRef<HTMLInputElement>(null),activeInput=useRef<HTMLInputElement|HTMLSelectElement>(null),lastSkipped=useRef<string|null>(null),progressId=useRef("");
 const {dragging,handlers}=useFileDrop(pickFile);
 const startedPending=useRef(false);
 useEffect(()=>{void listStaffImportFields(token).then(setFields).catch(()=>undefined)},[token]);
 useEffect(()=>{if(!analyzing)return;const timer=window.setInterval(()=>{if(progressId.current)void getStaffImportProgress(token,progressId.current).then(setPhase).catch(()=>undefined)},700);return()=>window.clearInterval(timer)},[analyzing,token]);
 const change=(id:string,patch:{value?:string;skip?:boolean})=>setDelta((d)=>({...d,[id]:{...d[id],...patch}}));
 function pickFile(f:File|null){setFile(f);if(f)void analyze(undefined,f)}
 useEffect(()=>{const pending=peekPendingImportFile();if(!pending||startedPending.current)return;startedPending.current=true;pickFile(pending)},[]);
 async function analyze(mapping?:Record<string,string|null>,forFile?:File){const target=forFile??file;if(!target)return;progressId.current=crypto.randomUUID();setAnalyzing(true);setPhase(null);setBusy(true);setError("");try{const next=await analyzeStaffFile(token,target,mapping,progressId.current);setData(next);setDelta(Object.fromEntries(next.reviews.map((r)=>[r.id,{value:r.value,skip:r.skip}])));setReviewIndex(0);setDeclinedCategoryIds(new Set());setDuplicateChoice("");setSavedDrafts({});if(next.status==="needs_mapping")setStage("mapping");else if(next.reviews.length)setStage("review");else setStage("summary");}catch(e){setError(e instanceof Error?e.message:tx("Não foi possível analisar."))}finally{setBusy(false);setAnalyzing(false);setPhase(null)}}
 async function apply(){if(!file||!data)return;setBusy(true);setError("");try{const r=await applyStaffImport(token,data.id,file,delta,false,[...declinedCategoryIds],duplicateChoice);setDone(tx("{inserted} inseridos, {updated} atualizados e {logins} logins criados.",{inserted:r.inserted,updated:r.updated,logins:r.loginsCreated}));setStage("done")}catch(e){setError(e instanceof Error?e.message:tx("Não foi possível importar."))}finally{setBusy(false)}}
 async function savePhone(reviewId:string){if(!data)return false;const phone=delta[reviewId]?.value??"";setBusy(true);setError("");try{const r=await createImportStaffDraft(token,data.id,reviewId,phone);setData(r.import);setSavedDrafts((s)=>({...s,[reviewId]:r.staff.id}));return true;}catch(e){setError(e instanceof Error?e.message:tx("Celular inválido."));return false;}finally{setBusy(false)}}
 const duplicateTotal=data?.reviews.filter((r)=>r.kind==="duplicate"&&!!r.existingData).length??0;
 const deadRows=useMemo(()=>{const rows=new Set<number>();if(data)for(const item of data.reviews){if(item.kind!=="duplicate")continue;const choice=delta[item.id]?.value||(item.existingData?duplicateChoice:"");if(delta[item.id]?.skip||choice==="keep")rows.add(item.row)}return rows},[data,delta,duplicateChoice]);
 const isDropped=(item:Review)=>item.kind!=="duplicate"&&deadRows.has(item.row);
 const reviews=useMemo(()=>{if(!data)return [];const filtered=data.reviews.filter((r)=>!(r.kind==="duplicate"&&!!r.existingData&&duplicateTotal>7)&&!(r.kind==="roomRole"&&(delta[r.id]?.value??r.value)!=="caretaker")&&!(r.kind==="bedroom"&&!r.original.trim())&&!isDropped(r)).slice().sort((a,b)=>REVIEW_ORDER.indexOf(a.kind)-REVIEW_ORDER.indexOf(b.kind)||a.row-b.row);const seen=new Set<string>(),collapsed:Review[]=[];for(const r of filtered){if(isSheetPhoneConflict(r)){const key=phoneConflictKey(r);if(seen.has(key))continue;seen.add(key);}collapsed.push(r);}return collapsed;},[data,delta,duplicateChoice,duplicateTotal,deadRows]);
 const current=reviews[reviewIndex]??null;
 const phoneConflictGroup=current&&isSheetPhoneConflict(current)&&data?data.reviews.filter((r)=>isSheetPhoneConflict(r)&&phoneConflictKey(r)===phoneConflictKey(current)).slice().sort((a,b)=>a.row-b.row):null;
 const batchDuplicatePending=duplicateTotal>7&&!duplicateChoice;
 useEffect(()=>{if(stage==="review"&&!current&&!batchDuplicatePending){if(reviews.length)setReviewIndex(reviews.length-1);else setStage("summary")}},[stage,current,reviews.length,batchDuplicatePending]);
 useEffect(()=>{if(stage==="review"&&current&&lastSkipped.current===current.id){lastSkipped.current=null;next()}},[stage,current,delta]);
 useEffect(()=>{if(stage==="review"&&current&&!isRichDup(current)&&!isSheetPhoneConflict(current))window.setTimeout(()=>activeInput.current?.focus(),80)},[stage,current?.id]);
 const completed=reviews.filter((r)=>{if(isSheetPhoneConflict(r)&&data){const group=data.reviews.filter((item)=>isSheetPhoneConflict(item)&&phoneConflictKey(item)===phoneConflictKey(r));return sheetConflictReady(group,delta);}return !!(delta[r.id]?.skip||(delta[r.id]?.value??r.value));}).length;
 const skippedRows=useMemo(()=>new Set(data?.reviews.filter((r)=>r.kind==="duplicate"&&((delta[r.id]?.value||(duplicateTotal>7?duplicateChoice:""))==="keep"||delta[r.id]?.skip)).map((r)=>r.row)??[]),[data,delta,duplicateChoice,duplicateTotal]);
 const labels=useMemo(()=>data?staffPreviewLabels(data,{bedrooms,teams,transports,categories,staff}):new Map<string,string>(),[data,bedrooms,teams,transports,categories,staff]);
 function reviewAccepts(item:Review,value:string):boolean{
  if(isSheetPhoneConflict(item))return sheetConflictReady(phoneConflictGroup??[],delta);
  if(item.kind==="duplicate")return !!value;
  if(item.kind==="phone"){const digits=value.replace(/\D/g,"");return digits.length===0||digits.length===11}
  return true;
 }
 function setValue(item:Review,value:string){setDelta((d)=>({...d,[item.id]:{...d[item.id],value,skip:false}}))}
 function skip(item:Review){lastSkipped.current=item.id;setDelta((d)=>({...d,[item.id]:{...d[item.id],skip:true}}))}
 function next(){if(reviewIndex+1<reviews.length)setReviewIndex((n)=>n+1);else setStage("summary")}
 async function continueReview(){if(!current)return;if(current.kind==="phone"&&!savedDrafts[current.id]){const value=delta[current.id]?.value??current.value??"";if(value.replace(/\D/g,"").length===11&&!(await savePhone(current.id)))return;}next()}
 function previous(){if(reviewIndex>0)setReviewIndex((n)=>n-1);else{setData(null);setFile(null);setStage("file")}}
 function downloadSkipped(){if(!data||!skippedRows.size)return;const rows=staffPreviewRows(data,delta,declinedCategoryIds,duplicateChoice).filter((r)=>skippedRows.has(Number(r.row))),columns=staffPreviewColumns(rows,labels,tx);const exported=rows.map((row)=>({...Object.fromEntries(columns.map((column)=>[tx(column.label),displayStaffValue(column.key,row[column.key],labels,tx)])),[tx("Motivo")]:row.duplicateChoice==="keep"?tx("Cadastro existente mantido"):tx("Revisão ignorada")}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(exported),tx("Não importados"));XLSX.writeFile(wb,`nao-importados-${data.fileName.replace(/\.[^.]+$/,"")}.xlsx`)}
 if(stage==="done")return <div className="admin-page import-page"><Breadcrumbs items={[{label:tx("Equipe"),onClick:onBack},{label:tx("Importação concluída")}]}/><section className="import-success"><span className="import-success__check"><CheckGlyph size={54}/></span><h1 className="admin-title">{tx("Importação concluída")}</h1><p className="admin-intro">{done}</p><button type="button" className="button button--primary" onClick={onBack}>{tx("Ver equipe")}</button></section></div>;
 return <div className="admin-page admin-page--wide import-page"><Breadcrumbs items={[{label:tx("Equipe"),onClick:onBack},{label:tx("Importar planilha")}]}/><header className="admin-head"><h1 className="admin-title"><img className="admin-title__icon" src={ICONS.importCampers} alt=""/> {tx("Importar equipe")}</h1></header>
  {stage!=="file"&&<StaffImportProgress stage={stage} reviewDone={completed} reviewTotal={reviews.length}/>}
  {error&&<p className="message message--error">{error}</p>}
  {analyzing&&<ImportPhaseBar phases={STAFF_PHASES} progress={phase}/>}
  {stage==="file"&&<section className={`import-drop${dragging?" import-drop--over":""}`} {...handlers}><img src={ICONS.staffPair} alt="" className="import-drop__icon"/><h2>{tx("Arraste o CSV ou Excel aqui")}</h2><p>{tx("Solte o arquivo nesta área ou escolha abaixo. A IA ajuda a reconhecer a planilha e você confirma as dúvidas antes de gravar.")}</p><input ref={fileInput} hidden type="file" accept=".csv,.xls,.xlsx,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e)=>pickFile(e.target.files?.[0]??null)}/><button type="button" className="button button--primary" disabled={busy} onClick={()=>fileInput.current?.click()}>{busy?tx("Analisando…"):file?file.name:tx("Escolher planilha")}</button><p className="cat-hint">{tx("Nada é importado nesta fase. Itens novos ficam em rascunho até você aplicar.")}</p></section>}
  {stage==="mapping"&&data&&<Mapping data={data} fields={fields} busy={busy} onConfirm={(m)=>void analyze(m)}/>}
  {stage==="review"&&data&&(batchDuplicatePending||current)&&<section className="import-review">
   <button type="button" className="icon-btn icon-btn--bare import-review__back" title={tx("Voltar")} aria-label={tx("Voltar")} onClick={previous}><BackGlyph size={22}/></button>
   {batchDuplicatePending?<><header className="import-review__head"><div><p className="import-review__eyebrow">{tx("Cadastros repetidos")}</p><h2>{tx("{count} pessoas já cadastradas",{count:duplicateTotal})}</h2></div></header><p className="admin-intro">{tx("Escolha a regra antes das outras revisões. A prévia, os contadores e os itens novos usarão esta decisão.")}</p><StaffDuplicateBatch value={duplicateChoice} onChange={(value)=>{setDuplicateChoice(value);if(!reviews.length)setStage("summary")}}/></>:current&&<><header className="import-review__head"><div><p className="import-review__eyebrow">{tx(phoneConflictGroup?"Celular repetido":REVIEW_LABEL[current.kind])}</p><h2>{phoneConflictGroup?formatBrazilPhoneClient(phoneConflictKey(current)||current.original):current.memberName}</h2></div>{current.kind!=="duplicate"&&<span className="checkin-progress">{reviewIndex+1}/{reviews.length}</span>}</header>
    {current.kind!=="duplicate"&&<p className="admin-intro">{tx("Corrija ou ignore as dúvidas; celular e quarto podem ficar vazios.")}</p>}
    {isRichDup(current)?<StaffDuplicateReview item={current} value={delta[current.id]?.value??""} labels={labels} onChange={(v)=>setValue(current,v)}/>:phoneConflictGroup?<StaffPhoneConflictReview group={phoneConflictGroup} delta={delta} onChange={(item,patch)=>setDelta((d)=>({...d,[item.id]:{...d[item.id],...patch}}))}/>:<><StaffReviewContext item={current}/><StaffReviewEditor item={current} value={delta[current.id]?.value??current.value} inputRef={activeInput} bedrooms={bedrooms} savedDraftId={savedDrafts[current.id]} onChange={(v)=>setValue(current,v)} onEditDraft={(id)=>window.open(`/staff/${id}/edit`,"_blank")}/></>}
    <div className="cat-form__actions import-review__actions">{!isRichDup(current)&&!phoneConflictGroup&&current.kind!=="phone"&&current.kind!=="roomRole"&&current.kind!=="inactive"&&(current.kind==="duplicate"?<button type="button" className="button button--warn" onClick={()=>skip(current)}>{tx("Pular")} <SkipGlyph/></button>:<button type="button" className="button button--secondary" onClick={()=>skip(current)}>{tx("Ignorar")}</button>)}<button type="button" className="button button--primary" disabled={busy||!reviewAccepts(current,delta[current.id]?.value??"")} onClick={()=>void continueReview()}>{tx("Continuar")}</button></div></>}
  </section>}
  {stage==="summary"&&data&&<section className="detail-card"><h2 className="detail-h2">{tx("Pronto para importar")}</h2><div className="import-stats"><span className="import-stats__success"><b>{data.preview.length-skippedRows.size}</b> {tx("pessoas")}</span>{createdCounters(data.createdItems).map((counter)=><span className="import-stats__success" key={counter.kind}><b>{counter.count}</b> {tx(counter.label)}</span>)}<span className="import-stats__warning"><b>{skippedRows.size}{skippedRows.size>0&&<button type="button" className="icon-btn icon-btn--bare import-download-icon" title={tx("Baixar não importados")} aria-label={tx("Baixar não importados")} onClick={downloadSkipped}><DownloadGlyph/></button>}</b> {tx("ignoradas")}</span></div>
   {unassignedColumns(data.columns).length>0&&<p className="cat-hint">{tx("{count} coluna(s) sem destino; os valores vão para as observações.",{count:unassignedColumns(data.columns).length})} <button className="link-btn" onClick={()=>setStage("mapping")}>{tx("Atribuir colunas")}</button></p>}
   {data.createdItems.some((item)=>item.kind==="categoryOption")&&<CategoryOptionReview record={data} categories={categories} declined={declinedCategoryIds} onChange={setDeclinedCategoryIds}/>}
   {data.createdItems.some((item)=>item.kind==="staff")&&<p className="import-created-staff">{createdStaffMessage(data.createdItems,tx)}</p>}
   <div className="import-preview-head"><h3>{tx("Prévia")}</h3><button type="button" className={`import-preview-toggle${previewOpen?" is-visible":""}`} aria-label={previewOpen?tx("Ocultar prévia"):tx("Mostrar prévia")} aria-pressed={previewOpen} title={previewOpen?tx("Ocultar prévia"):tx("Mostrar prévia")} onClick={()=>setPreviewOpen((v)=>!v)}><EyeGlyph/></button></div>
   {previewOpen&&<StaffPreview data={data} delta={delta} skippedRows={skippedRows} labels={labels} declinedCategoryIds={declinedCategoryIds} duplicateChoice={duplicateChoice}/>} <div className="cat-form__actions"><button type="button" className="button button--secondary" onClick={()=>reviews.length?setStage("review"):setStage("file")}>{tx("Voltar")}</button><button type="button" className="button button--primary" disabled={busy||(duplicateTotal>7&&!duplicateChoice)} onClick={apply}>{busy?tx("Importando…"):tx("Aplicar importação")}</button></div></section>}
 </div>
}

function StaffImportProgress({stage,reviewDone,reviewTotal}:{stage:Stage;reviewDone:number;reviewTotal:number}){
 const {tx}=useI18n();
 const index=stage==="mapping"?1:stage==="review"?2:3;
 const pct=stage==="review"&&reviewTotal?33+Math.round((reviewDone/reviewTotal)*34):index*33;
 return <div className="import-progress" aria-label={tx("Progresso {pct}%",{pct:Math.min(pct,100)})}><span style={{width:`${Math.min(pct,100)}%`}}/><ol><li className={index>=1?"on":""}>{tx("Colunas")}</li><li className={index>=2?"on":""}>{tx("Revisão")}</li><li className={index>=3?"on":""}>{tx("Prévia")}</li></ol></div>;
}

function StaffReviewContext({item}:{item:Review}){
 const {tx}=useI18n();
 const parts=[tx("Linha {row}",{row:item.row}),item.context||null].filter((p):p is string=>!!p);
 return <div className="import-review__context">{parts.map((p)=><span key={p}>{p}</span>)}{item.original&&<p><b>{tx("Na planilha:")}</b> {item.original}</p>}</div>;
}

function StaffReviewEditor({item,value,inputRef,bedrooms,savedDraftId,onChange,onEditDraft}:{item:Review;value:string;inputRef:React.RefObject<HTMLInputElement|HTMLSelectElement|null>;bedrooms:{id:string;name:string}[];savedDraftId:string|undefined;onChange:(v:string)=>void;onEditDraft:(id:string)=>void}){
 const {tx}=useI18n();
 if(item.kind==="duplicate")return <label className="cat-field"><span className="cat-field__label">{tx("Esta pessoa")}</span><select ref={inputRef as React.RefObject<HTMLSelectElement>} className="cat-input" value={value} onChange={(e)=>onChange(e.target.value)}><option value="">{tx("Escolha…")}</option>{item.existingId&&<option value={item.existingId}>{tx("Mesma pessoa: {name} {phone}",{name:item.existingName??"",phone:item.existingPhone?formatBrazilPhoneClient(item.existingPhone):""})}</option>}{item.options?.map((o)=><option key={o.id} value={o.id}>{tx("Mesma pessoa: {name} {phone}",{name:o.label,phone:""})}</option>)}<option value="insert">{tx("Pessoa diferente: inserir")}</option></select></label>;
 if(item.kind==="bedroom")return <label className="cat-field"><span className="cat-field__label">{tx("Quarto")}</span><select ref={inputRef as React.RefObject<HTMLSelectElement>} className="cat-input" value={value} onChange={(e)=>onChange(e.target.value)}><option value="">{tx("Sem quarto")}</option>{bedrooms.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>;
 if(item.kind==="roomRole")return <label className="cat-field"><span className="cat-field__label">{tx("Função no quarto")}</span><select ref={inputRef as React.RefObject<HTMLSelectElement>} className="cat-input" value={value} onChange={(e)=>onChange(e.target.value)}><option value="helper">{tx("Auxiliar")}</option><option value="caretaker">{tx("Líder")}</option></select></label>;
 if(item.kind==="inactive")return <label className="cat-field"><span className="cat-field__label">{tx("Situação")}</span><select ref={inputRef as React.RefObject<HTMLSelectElement>} className="cat-input" value={value} onChange={(e)=>onChange(e.target.value)}><option value="false">{tx("Inativo")}</option><option value="true">{tx("Ativo")}</option></select></label>;
 if(savedDraftId)return <div className="import-review-phone"><span className="import-review-done"><CheckGlyph/> <button className="icon-btn icon-btn--bare" title={tx("Editar cadastro")} aria-label={tx("Editar cadastro")} onClick={()=>onEditDraft(savedDraftId)}><img className="pencil-icon" src={ICONS.pencil} alt=""/></button></span></div>;
 return <div className="import-review-phone"><label className="cat-field cat-field--grow"><span className="cat-field__label">{tx("Celular")}</span><PhoneInput value={maskBrazilPhone(value)} onChange={onChange} inputRef={inputRef as React.RefObject<HTMLInputElement|null>}/></label></div>;
}

const STAFF_DUP_FIELDS=["name","phone","email","document","birthDate","active","roomRole","team","bedroom","transportation","probableGender","allergies","drugAllergies","healthIssues","foodRestrictions","healthNotes","organizer","checkinHelper","vestHelper","scoreHelper","gameOrganizer"];
function staffDupEntries(data:Record<string,unknown>|undefined){return STAFF_DUP_FIELDS.flatMap((key)=>{const value=data?.[key];return value==null||value===""||(Array.isArray(value)&&!value.length)?[]:[{key,value}]})}
function staffDupLabel(key:string){return STAFF_PREVIEW_COLUMNS.find((column)=>column.key===key)?.label??key}
function staffDupText(key:string,value:unknown,labels:Map<string,string>,tx:(pt:string,vars?:Record<string,string|number>)=>string=(s)=>s){return displayStaffValue(key,value,labels,tx)}
function StaffDuplicateCard({title,data,other,labels,source,selected,onClick}:{title:string;data:Record<string,unknown>|undefined;other:Record<string,unknown>|undefined;labels:Map<string,string>;source:"system"|"sheet";selected:boolean;onClick:()=>void}){const {tx}=useI18n();return <button type="button" className={`import-duplicate-card import-duplicate-card--${source}${selected?" is-selected":""}`} aria-pressed={selected} onClick={onClick}><strong>{title}</strong><table className="import-duplicate-card__table"><tbody>{staffDupEntries(data).map(({key,value})=>{const different=!!other&&staffDupText(key,value,labels,tx)!==staffDupText(key,other[key],labels,tx);return <tr key={key} className={different?"is-different":undefined}><th>{tx(staffDupLabel(key))}</th><td>{staffDupText(key,value,labels,tx)}</td></tr>})}</tbody></table></button>}
function StaffDuplicateReview({item,value,labels,onChange}:{item:StaffImport["reviews"][number];value:string;labels:Map<string,string>;onChange:(value:string)=>void}){const {tx}=useI18n();const merged=value==="merge";return <div className="import-duplicate"><p className="admin-intro">{tx("Já existe um cadastro com esta chave. Quarto, time, função e transporte atuais serão mantidos.")}</p>{merged?<div className="import-duplicate-merged"><strong>{tx("Versão mesclada")}</strong><table className="import-duplicate-card__table"><tbody>{staffDupEntries(item.mergedData).map(({key,value:fieldValue})=>{const old=item.existingData?.[key],incoming=item.incomingData?.[key],sourceKey=staffDupText(key,old,labels,tx)===staffDupText(key,fieldValue,labels,tx)?"Sistema":staffDupText(key,incoming,labels,tx)===staffDupText(key,fieldValue,labels,tx)?"Planilha":"Ambos";return <tr key={key}><th>{tx(staffDupLabel(key))}</th><td>{staffDupText(key,fieldValue,labels,tx)}</td><td><small className={`import-source import-source--${sourceKey==="Sistema"?"system":sourceKey==="Planilha"?"sheet":"both"}`}>{tx(sourceKey)}</small></td></tr>})}</tbody></table></div>:<div className="import-duplicate-grid"><StaffDuplicateCard title={tx("Cadastro atual")} data={item.existingData} other={item.incomingData} labels={labels} source="system" selected={value==="keep"} onClick={()=>onChange("keep")}/><span className="import-duplicate-choice">{tx("ou")}</span><StaffDuplicateCard title={tx("Planilha")} data={item.incomingData} other={item.existingData} labels={labels} source="sheet" selected={value==="update"} onClick={()=>onChange("update")}/></div>}{item.mergeAvailable&&<button type="button" className={`button ${merged?"button--primary":"button--secondary"}`} onClick={()=>onChange(merged?"":"merge")}>{merged?tx("Mesclando as versões"):tx("Mesclar informações")}</button>}</div>}
function StaffDuplicateBatch({value,onChange}:{value:"update"|"keep"|"merge"|"";onChange:(value:"update"|"keep"|"merge")=>void}){const {tx}=useI18n();return <section className="import-duplicate-batch"><h3>{tx("Cadastros repetidos")}</h3><p>{tx("Qual regra deve valer para todos?")}</p><div className="import-duplicate-batch__options">{([['update','Atualizar com a planilha'],['keep','Manter os cadastros atuais'],['merge','Mesclar as informações']] as const).map(([key,label])=><button type="button" key={key} className={value===key?"is-selected":undefined} aria-pressed={value===key} onClick={()=>onChange(key)}>{tx(label)}</button>)}</div></section>}
function StaffPhoneConflictReview({group,delta,onChange}:{group:Review[];delta:Delta;onChange:(item:Review,patch:{value?:string;skip?:boolean})=>void}){
 const {tx}=useI18n();
 return <div className="import-duplicate">
  <p className="admin-intro">{tx("Este celular aparece em mais de uma linha. Troque o número, limpe o campo ou ignore uma das pessoas.")}</p>
  <div className="import-phone-conflict">
   {group.map((item)=>{const d=delta[item.id],ignored=!!d?.skip,raw=d?.value??"",display=raw==="blank"?"":!raw||raw==="keep-phone"?formatBrazilPhoneClient(phoneConflictKey(item)||item.original):maskBrazilPhone(raw);return <div key={item.id} className={`import-phone-conflict__row${ignored?" is-ignored":""}`}>
    <span className="cat-field__label">{tx("Linha {row} · {name}",{row:item.row,name:item.memberName})}</span>
    <PhoneInput value={display} disabled={ignored} onChange={(value)=>onChange(item,{value:conflictDigits(value)?value:"blank",skip:false})} onClear={()=>onChange(item,{value:"blank",skip:false})}/>
    <Toggle checked={ignored} onChange={(skip)=>onChange(item,{skip})} label={tx("Ignorar")}/>
    {ignored&&<p className="cat-hint import-phone-conflict__hint">{tx("Esta pessoa não será inserida.")}</p>}
   </div>;})}
  </div>
  <p className="cat-hint">{tx("Quem ficar sem celular é cadastrado mesmo assim, mas não consegue entrar no sistema até alguém preencher o número.")}</p>
 </div>;
}

const CREATED_COUNTER_LABEL:Record<string,[string,string]>={transportation:["transporte novo","transportes novos"],team:["time novo","times novos"],bedroom:["quarto novo","quartos novos"]};
function createdCounters(items:{kind:string}[]){return Object.entries(CREATED_COUNTER_LABEL).flatMap(([kind,names])=>{const count=items.filter((item)=>item.kind===kind).length;return count?[{kind,count,label:count===1?names[0]:names[1]}]:[]})}
function createdStaffMessage(items:{kind:string;label:string}[],tx:(pt:string,vars?:Record<string,string|number>)=>string){const names=items.filter((item)=>item.kind==="staff").map((item)=>item.label);return names.length===1?tx("Cadastro já criado na revisão: {name}.",{name:names[0]}):tx("Cadastros já criados na revisão: {names}.",{names:names.join(", ")})}
function categoryIcon(cat:Category|undefined){if(cat?.key==="alergia-medicamentos")return <NoPillIcon/>;return cat?.emoji??"🏷️"}
function CategoryOptionReview({record,categories,declined,onChange}:{record:StaffImport;categories:Category[];declined:Set<string>;onChange:(ids:Set<string>)=>void}){const {tx}=useI18n();const items=record.createdItems.filter((item)=>item.kind==="categoryOption"),categoryOf=(item:(typeof items)[number])=>item.label.includes(": ")?item.label.slice(0,item.label.indexOf(": ")):tx("Categoria"),valueOf=(item:(typeof items)[number])=>item.label.includes(": ")?item.label.slice(item.label.indexOf(": ")+2):item.label;const examplesOf=(id:string)=>{const raws=new Set(record.dictionaries.filter((entry)=>entry.value===id&&entry.raw).map((entry)=>entry.raw)),examples:{row:number;raw:string}[]=[];for(const row of record.preview){const notes=row.categoryNotesById&&typeof row.categoryNotesById==="object"?row.categoryNotesById as Record<string,string[]>:{};if(!notes[id]?.length)continue;const raw=[...raws].find((value)=>notes[id].some((note)=>note.includes(value)))??[...raws][0];if(raw&&!examples.some((example)=>example.raw===raw))examples.push({row:Number(row.row),raw});if(examples.length===3)break}return examples};const toggle=(id:string,checked:boolean)=>{const next=new Set(declined);if(checked)next.delete(id);else next.add(id);onChange(next)};return <section className="import-category-review"><div><h3>{tx("Novas opções encontradas")}</h3><p>{tx("Marque o que deve entrar nas listas.")}</p></div><div className="import-category-review__table-wrap"><table className="import-category-review__table"><thead><tr><th>{tx("Inserir")}</th><th>{tx("Lista")}</th><th>{tx("Nova opção")}</th><th>{tx("Exemplos da planilha")}</th></tr></thead><tbody>{items.map((item)=>{const topic=categoryOf(item),cat=categories.find((category)=>category.name.trim().toLowerCase()===topic.trim().toLowerCase()),checked=!declined.has(item.id);return <tr key={item.id} className={checked?undefined:"is-declined"}><td><input type="checkbox" checked={checked} aria-label={tx("Inserir {value}",{value:valueOf(item)})} onChange={(event)=>toggle(item.id,event.target.checked)}/></td><td><span className="import-category-review__topic">{categoryIcon(cat)} {topic}</span></td><td><strong>{valueOf(item)}</strong></td><td>{examplesOf(item.id).map((example)=><span className="import-category-review__example" key={`${example.row}-${example.raw}`}><strong>{tx("Linha {row}:",{row:example.row})}</strong> {example.raw}</span>)}</td></tr>})}</tbody></table></div>{declined.size>0&&<p className="import-category-review__warning">{tx("As informações desmarcadas serão movidas para as observações de cada pessoa.")}</p>}</section>}

const STAFF_PREVIEW_COLUMNS=[{key:"row",label:"Linha"},{key:"duplicateSource",label:"Origem"},{key:"name",label:"Nome"},{key:"phone",label:"Celular"},{key:"email",label:"E-mail"},{key:"document",label:"Documento"},{key:"birthDate",label:"Nascimento"},{key:"probableGender",label:"Sexo"},{key:"active",label:"Ativo"},{key:"roomRole",label:"Função"},{key:"team",label:"Time"},{key:"bedroom",label:"Quarto"},{key:"transportation",label:"Transporte"},{key:"organizer",label:"Organizador"},{key:"checkinHelper",label:"Check-in"},{key:"vestHelper",label:"Coletes"},{key:"scoreHelper",label:"Placar"},{key:"gameOrganizer",label:"Jogos"},{key:"allergies",label:"Alergias"},{key:"drugAllergies",label:"Alergia a remédios"},{key:"healthIssues",label:"Condições de saúde"},{key:"foodRestrictions",label:"Restrição alimentar"},{key:"healthNotes",label:"Observações"}];
function staffPreviewLabels(data:StaffImport,collections:{bedrooms:{id:string;name:string}[];teams:{id:string;name:string}[];transports:{id:string;label:string}[];categories:Category[];staff:{id:string;name:string}[]}){const labels=new Map<string,string>();for(const category of collections.categories)for(const option of category.options)labels.set(option.id,option.label);for(const room of collections.bedrooms)labels.set(room.id,room.name);for(const team of collections.teams)labels.set(team.id,team.name);for(const transport of collections.transports)labels.set(transport.id,transport.label);for(const member of collections.staff)labels.set(member.id,member.name);for(const entry of data.dictionaries)if(typeof entry.value==="string"&&entry.value&&!labels.has(entry.value))labels.set(entry.value,entry.label);for(const item of data.createdItems)if(!labels.has(item.id))labels.set(item.id,item.label);return labels}
function staffPreviewRows(data:StaffImport,delta:Delta,declined:Set<string>,duplicateChoice:"update"|"keep"|"merge"|""=""){const rows=data.preview.map((source)=>{const row={...source},notesById=row.categoryNotesById&&typeof row.categoryNotesById==="object"?row.categoryNotesById as Record<string,string[]>:{},notes:string[]=[];for(const field of ["allergies","drugAllergies","healthIssues"] as const){const ids=Array.isArray(row[field])?row[field] as string[]:[],removed=ids.filter((id)=>declined.has(id));row[field]=ids.filter((id)=>!declined.has(id));for(const id of removed)notes.push(...(notesById[id]??[]))}if(notes.length)row.healthNotes=[String(row.healthNotes??"").trim(),...new Set(notes)].filter(Boolean).join(" ");return row});for(const review of data.reviews){const d=delta[review.id]??{},row=rows.find((item)=>Number(item.row)===review.row);if(!row)continue;const value=d.value??review.value;if(review.kind==="phone")row.phone=d.skip?null:value||null;else if(review.kind==="bedroom")row.bedroom=d.skip?null:value||null;else if(review.kind==="roomRole")row.roomRole=value==="caretaker"?"caretaker":"helper";else if(review.kind==="inactive")row.active=value!=="false";else if(review.kind==="duplicate"){const choice=value||(review.existingData?duplicateChoice:"");if(!review.existingData){if(d.skip){row.blocked=true;row.duplicateSource="Ignorado";}else{row.blocked=false;row.existingStaffId=null;if(!choice||choice==="keep-phone")row.duplicateSource="Fica com o celular";else if(choice==="blank"||!conflictDigits(choice)){row.phone=null;row.duplicateSource="Sem celular";}else{row.phone=choice;row.duplicateSource="Novo celular";}}}else if(d.skip)row.blocked=true;else if(choice==="keep"){row.blocked=true;row.duplicateSource="Cadastro atual";if(review.existingData)Object.assign(row,review.existingData,{row:row.row,blocked:true,duplicateSource:"Cadastro atual"});}else if(choice==="update"){row.blocked=false;row.existingStaffId=review.existingId??null;row.duplicateSource="Planilha";}else if(choice==="merge"&&review.mergedData)Object.assign(row,review.mergedData,{row:row.row,blocked:false,existingStaffId:review.existingId??null,duplicateSource:"Mesclado"});else if(choice==="insert")row.existingStaffId=null;else if(choice)row.existingStaffId=choice}}for(const review of data.reviews)if(review.kind==="duplicate"&&review.existingData){const row=rows.find((item)=>Number(item.row)===review.row);if(row&&!row.duplicateSource)row.duplicateSource="Pendente"}return rows}
function staffPreviewColumns(rows:Record<string,unknown>[],labels:Map<string,string>,tx:(pt:string,vars?:Record<string,string|number>)=>string=(s)=>s){return STAFF_PREVIEW_COLUMNS.filter((column)=>column.key==="row"||column.key==="name"||rows.some((row)=>displayStaffValue(column.key,row[column.key],labels,tx)!=="—"))}
function displayStaffValue(key:string,value:unknown,labels:Map<string,string>,tx:(pt:string,vars?:Record<string,string|number>)=>string= (s)=>s):string{if(value==null||value==="")return "—";if(Array.isArray(value))return value.map((item)=>displayStaffValue("",item,labels,tx)).join(", ")||"—";if(typeof value==="boolean")return value?tx("Sim"):tx("Não");const text=String(value),label=labels.get(text);if(label&&!ID.test(label))return label;if(/^\d{4}-\d{2}-\d{2}$/.test(text)){const[y,m,d]=text.split("-");return `${d}/${m}/${y}`}if(key==="phone"){const digits=text.replace(/\D/g,"").replace(/^55/,"");return digits.length===11?formatBrazilPhoneClient(text):text}if(key==="weightKg")return `${text.replace(".",",")} kg`;if(key==="probableGender")return value==="F"?tx("Feminino"):value==="M"?tx("Masculino"):"—";if(key==="roomRole")return value==="caretaker"?tx("Líder"):tx("Auxiliar");if(key==="duplicateSource")return tx(text);if(ID.test(text))return "—";return text}
const PREVIEW_LIMIT=56;
function StaffPreview({data,delta,skippedRows,labels,declinedCategoryIds,duplicateChoice}:{data:StaffImport;delta:Delta;skippedRows:Set<number>;labels:Map<string,string>;declinedCategoryIds:Set<string>;duplicateChoice:"update"|"keep"|"merge"|""}){const {tx}=useI18n();const [expanded,setExpanded]=useState<Set<string>>(()=>new Set()),rows=staffPreviewRows(data,delta,declinedCategoryIds,duplicateChoice),imported=rows.filter((row)=>!skippedRows.has(Number(row.row))),columns=staffPreviewColumns(imported,labels,tx),longColumns=new Set(columns.filter((column)=>rows.some((row)=>displayStaffValue(column.key,row[column.key],labels,tx).length>PREVIEW_LIMIT)).map((column)=>column.key)),toggle=(key:string)=>setExpanded((current)=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next});return <div className="import-table-wrap"><table className="import-table"><thead><tr>{columns.map((column)=><th key={column.key} className={expanded.has(column.key)?"import-table__column--expanded":undefined}>{longColumns.has(column.key)?<button type="button" className={`import-table__column-toggle${expanded.has(column.key)?" is-expanded":""}`} aria-pressed={expanded.has(column.key)} title={expanded.has(column.key)?tx("Recolher coluna"):tx("Mostrar o conteúdo completo desta coluna")} onClick={()=>toggle(column.key)}>{tx(column.label)} <span><EllipsisGlyph size={13}/></span></button>:tx(column.label)}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((row,i)=><tr key={`${row.row}-${i}`} className={skippedRows.has(Number(row.row))?"import-table__row--out":undefined}>{columns.map((column)=>{const cell=displayStaffValue(column.key,row[column.key],labels,tx),long=cell.length>PREVIEW_LIMIT,isExpanded=expanded.has(column.key);return <td key={column.key} className={isExpanded?"import-table__column--expanded":undefined}>{long&&!isExpanded?<button type="button" className="import-table__truncated" title={tx("Mostrar o conteúdo completo desta coluna")} onClick={()=>toggle(column.key)}>{`...${cell.slice(-(PREVIEW_LIMIT-3))}`}</button>:cell}</td>})}</tr>)}</tbody></table>{rows.length>200&&<p className="cat-hint">{tx("Mostrando as primeiras 200 linhas.")}</p>}</div>}

function Mapping({data,fields,busy,onConfirm}:{data:StaffImport;fields:{key:StaffImportField;label:string}[];busy:boolean;onConfirm:(m:Record<string,string|null>)=>void}){const {tx}=useI18n();const [map,setMap]=useState<Record<string,string|null>>(()=>Object.fromEntries(data.columns.map((c)=>[c.source,c.target]))),used=new Set(Object.values(map).filter(Boolean)),hasName=used.has("name"),unknown=data.columns.filter((c)=>!map[c.source]&&c.samples.length&&!isIgnoredColumn(c.source)),nameSource=Object.entries(map).find(([,t])=>t==="name")?.[0]??"",nameColumn=data.columns.find((c)=>c.source===nameSource),pickName=(source:string)=>setMap((m)=>{const next={...m};for(const[s,t]of Object.entries(next))if(t==="name")next[s]=null;if(source)next[source]="name";return next});return <section className="detail-card"><h2 className="detail-h2">{hasName?tx("Colunas sem destino"):tx("Escolha a coluna de Nome")}</h2>{hasName?<p className="admin-intro">{tx("Atribua um destino ou deixe os valores irem para as observações.")}</p>:<p className="admin-intro">{tx("Não encontrei o ")}<b>{tx("Nome")}</b>.</p>}{!hasName&&<div className="import-map-row"><div><strong>{tx("Nome")}</strong><small>{nameColumn?nameColumn.samples.slice(0,5).join(" · "):tx("escolha a coluna com os nomes")}</small></div><select className="cat-input" autoFocus value={nameSource} onChange={(e)=>pickName(e.target.value)}><option value="">{tx("Escolha a coluna…")}</option>{data.columns.filter((c)=>c.samples.length&&!isIgnoredColumn(c.source)).map((c)=><option key={c.source} value={c.source}>{c.source}</option>)}</select></div>}{unknown.length>0&&<details open={hasName}><summary className="link-btn">{tx("{count} colunas sem destino",{count:unknown.length})}</summary>{unknown.map((c)=><div className="import-map-row" key={c.source}><div><strong>{c.source}</strong><small>{c.samples.slice(0,5).join(" · ")||tx("sem amostra")}</small></div><select className="cat-input" value={map[c.source]??""} onChange={(e)=>setMap((m)=>({...m,[c.source]:e.target.value||null}))}><option value="">{tx("Ignorar")}</option>{fields.map((f)=><option key={f.key} value={f.key} disabled={used.has(f.key)&&map[c.source]!==f.key}>{tx(f.label)}</option>)}</select></div>)}</details>}{data.error&&<p className="message message--error">{data.error}</p>}<button className="button button--primary" disabled={busy||!hasName} onClick={()=>onConfirm(map)}>{busy?tx("Preparando…"):tx("Continuar")}</button></section>}

