import { useEffect, useMemo, useState } from "react";
import Breadcrumbs from "../../components/Breadcrumbs";
import { useCollectionOrEmpty } from "../../store";
import { useLabelOf } from "../../store/derive";
import { analyzeStaffFile, applyStaffImport, createImportStaffDraft, listStaffImportFields, type StaffImport, type StaffImportField } from "../../api/staffImports";
import { formatBrazilPhoneClient } from "../../phoneFormat";

export default function StaffImportPage({token,onBack}:{token:string;onBack:()=>void}){
 const [file,setFile]=useState<File|null>(null),[data,setData]=useState<StaffImport|null>(null),[fields,setFields]=useState<{key:StaffImportField;label:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[delta,setDelta]=useState<Record<string,{value?:string;skip?:boolean}>>({}),[welcomes,setWelcomes]=useState(false),[done,setDone]=useState("");
 const [savedDrafts,setSavedDrafts]=useState<Record<string,string>>({});
 const bedrooms=useCollectionOrEmpty("bedrooms"),labelOf=useLabelOf();
 useEffect(()=>{void listStaffImportFields(token).then(setFields)},[token]);
 const change=(id:string,patch:{value?:string;skip?:boolean})=>setDelta((d)=>({...d,[id]:{...d[id],...patch}}));
 async function analyze(mapping?:Record<string,string|null>){if(!file)return;setBusy(true);setError("");try{setData(await analyzeStaffFile(token,file,mapping));}catch(e){setError(e instanceof Error?e.message:"Não foi possível analisar.")}finally{setBusy(false)}}
 async function apply(){if(!file||!data)return;setBusy(true);setError("");try{const r=await applyStaffImport(token,data.id,file,delta,welcomes);setDone(`${r.inserted} inseridos, ${r.updated} atualizados e ${r.loginsCreated} logins criados.`)}catch(e){setError(e instanceof Error?e.message:"Não foi possível importar.")}finally{setBusy(false)}}
 async function savePhone(reviewId:string){if(!data)return;const phone=delta[reviewId]?.value??"";setBusy(true);setError("");try{const r=await createImportStaffDraft(token,data.id,reviewId,phone);setData(r.import);setSavedDrafts((s)=>({...s,[reviewId]:r.staff.id}));}catch(e){setError(e instanceof Error?e.message:"Celular inválido.")}finally{setBusy(false)}}
 const unresolved=useMemo(()=>data?.reviews.filter((r)=>!delta[r.id]?.value&&!delta[r.id]?.skip&&r.kind==="duplicate")??[],[data,delta]);
 if(done)return <div className="admin-page"><Breadcrumbs items={[{label:"Equipe",onClick:onBack},{label:"Importar"}]}/><div className="admin-empty"><h1>Importação concluída</h1><p>{done}</p><button className="button button--primary" onClick={onBack}>Ver equipe</button></div></div>;
 return <div className="admin-page"><Breadcrumbs items={[{label:"Equipe",onClick:onBack},{label:"Importar planilha"}]}/><header className="admin-head"><h1 className="admin-title">Importar equipe</h1></header>
  <p className="admin-intro">A IA ajuda a reconhecer a planilha. Você confirma as dúvidas antes de gravar.</p>{error&&<p className="message message--error">{error}</p>}
  {!data&&<section className="detail-card"><label className="cat-field"><span className="cat-field__label">CSV ou Excel</span><input type="file" accept=".csv,.xlsx,.xls" onChange={(e)=>setFile(e.target.files?.[0]??null)}/></label><button className="button button--primary" disabled={!file||busy} onClick={()=>analyze()}>{busy?"Analisando…":"Analisar planilha"}</button></section>}
  {data?.status==="needs_mapping"&&<Mapping data={data} fields={fields} busy={busy} onConfirm={(m)=>analyze(m)}/>} 
  {data&&["review","ready"].includes(data.status)&&<><section className="detail-card"><h2 className="detail-h2">Revisão</h2><p className="admin-intro">Algumas coisas eu não consegui decidir sozinho. Corrija ou pule; celular e quarto podem ficar vazios.</p>{data.reviews.map((r)=><div className="import-review-row" key={r.id}><div><strong>Linha {r.row} · {r.memberName}</strong><small>{r.context||r.original||"sem valor"}</small></div>{r.kind==="duplicate"?<select className="cat-input" autoFocus value={delta[r.id]?.value??""} onChange={(e)=>change(r.id,{value:e.target.value})}><option value="">Escolha…</option>{r.existingId&&<option value={r.existingId}>Mesma pessoa: {r.existingName} {r.existingPhone?formatBrazilPhoneClient(r.existingPhone):""}</option>}{r.options?.map((o)=><option key={o.id} value={o.id}>Mesma pessoa: {o.label}</option>)}<option value="insert">Pessoa diferente: inserir</option></select>:r.kind==="bedroom"?<select className="cat-input" autoFocus value={delta[r.id]?.value??r.value} onChange={(e)=>change(r.id,{value:e.target.value})}><option value="">Sem quarto</option>{bedrooms.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select>:r.kind==="roomRole"?<select className="cat-input" value={delta[r.id]?.value??r.value} onChange={(e)=>change(r.id,{value:e.target.value})}><option value="helper">Auxiliar</option><option value="caretaker">Líder</option></select>:r.kind==="inactive"?<select className="cat-input" value={delta[r.id]?.value??r.value} onChange={(e)=>change(r.id,{value:e.target.value})}><option value="false">Inativo</option><option value="true">Ativo</option></select>:savedDrafts[r.id]?<span className="import-review-done">✓ <button className="icon-btn icon-btn--bare" title="Editar cadastro" onClick={()=>window.open(`/staff/${savedDrafts[r.id]}/edit`,"_blank")}>✏️</button></span>:<span className="import-review-phone"><input className="cat-input" autoFocus placeholder="(DDD) 9 9999-9999" value={delta[r.id]?.value??""} onChange={(e)=>change(r.id,{value:e.target.value})}/><button className="button button--primary" disabled={busy||!(delta[r.id]?.value)} onClick={()=>void savePhone(r.id)}>Salvar</button></span>}<button className="button button--secondary" onClick={()=>change(r.id,{skip:true,value:""})}>Pular</button></div>)}</section>
   <section className="detail-card"><h2 className="detail-h2">Prévia</h2><p>{data.preview.length} pessoas · {data.preview.filter((r)=>r.phone).length} logins · {data.createdItems.length} cadastros auxiliares criados</p><details><summary className="link-btn">Ver planilha tratada</summary><div className="table-scroll"><table><thead><tr><th>Linha</th><th>Nome</th><th>Celular</th><th>Time</th><th>Quarto</th><th>Transporte</th><th>Função</th></tr></thead><tbody>{data.preview.map((r)=><tr key={String(r.row)}><td>{String(r.row)}</td><td>{String(r.name)}</td><td>{r.phone?formatBrazilPhoneClient(String(r.phone)):"—"}</td><td>{r.team?labelOf(String(r.team)):"—"}</td><td>{r.bedroom?bedrooms.find((b)=>b.id===r.bedroom)?.name:"—"}</td><td>{r.transportation?labelOf(String(r.transportation)):"—"}</td><td>{r.roomRole==="caretaker"?"Líder":"Auxiliar"}</td></tr>)}</tbody></table></div></details><label className="check-row"><input type="checkbox" checked={welcomes} onChange={(e)=>setWelcomes(e.target.checked)}/> Enviar boas-vindas depois da importação</label><button className="button button--primary" disabled={busy||unresolved.length>0} onClick={apply}>{busy?"Importando…":"Aplicar importação"}</button>{unresolved.length>0&&<p className="message message--error">Resolva {unresolved.length} possível duplicidade.</p>}</section></>}
 </div>
}
function Mapping({data,fields,busy,onConfirm}:{data:StaffImport;fields:{key:StaffImportField;label:string}[];busy:boolean;onConfirm:(m:Record<string,string|null>)=>void}){const [map,setMap]=useState<Record<string,string|null>>(()=>Object.fromEntries(data.columns.map((c)=>[c.source,c.target])));return <section className="detail-card"><h2 className="detail-h2">Confirme as colunas</h2>{data.error&&<p className="message message--error">{data.error}</p>}{data.columns.map((c)=><div className="import-map-row" key={c.source}><div><strong>{c.source}</strong><small>{c.samples.slice(0,5).join(" · ")||"sem amostra"}</small></div><select className="cat-input" value={map[c.source]??""} onChange={(e)=>setMap((m)=>({...m,[c.source]:e.target.value||null}))}><option value="">Ignorar</option>{fields.map((f)=><option key={f.key} value={f.key}>{f.label}</option>)}</select></div>)}<button className="button button--primary" disabled={busy||!Object.values(map).includes("name")} onClick={()=>onConfirm(map)}>{busy?"Preparando…":"Confirmar e preparar"}</button></section>}
